// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpowzyhmoafiwtyvlzdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwb3d6eWhtb2FmaXd0eXZsemRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjgyODksImV4cCI6MjA2MTQwNDI4OX0.8UJC-tO9PE_GZGafd1hevW7Jp_TZmcddeImFAh_6aBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);